sudo: required
language: python
services:
  - docker
before_install:
  - docker build -t frolvlad/alpine-python2 .
  - docker run frolvlad/alpine-python2 /bin/sh -C
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - pytest
